#!/usr/bin/env bash
#manage
case "$1" in
  start)
    bash manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    bash manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

exit 0